# Makefile
CFLAGS = -Wall -Werror -Wextra -pedantic -std=gnu89
question_0: 0-linear.c tests/test_linear.c search_algos.h
	echo "making quetion_0"
	gcc ${CFLAGS} 0-linear.c tests/test_linear.c -o executables/question_0
	chmod u+x executables/question_0
