CC = gcc -Wall -Werror -Wextra -pedantic -std=gnu89

test_0: ../_putchar.c 0-main.c ../0-puts_recursion.c
	$(CC) ../_putchar.c 0-main.c ../0-puts_recursion.c -o test0 
test_1: ../_putchar.c 1-main.c ../1-print_rev_recursion.c
	$(CC) ../_putchar.c 1-main.c ../1-print_rev_recursion -o test1
test_2: ../_putchar.c 2-main.c ../2-strlen_recursion.c 
	$(CC) ../_putchar.c 2-main.c ../2-strlen_recursion.c -o test2
test_3: ../_putchar.c 3-main.c ../3-factorial.c 
	$(CC) ../_putchar.c 3-main.c ../3-factorial.c -o test3
test_4: ../_putchar.c 4-main.c ../4-pow_recursion.c 
	$(CC) ../_putchar.c 4-main.c ../4-pow_recursion.c -o test4
test_5: ../_putchar.c 5-main.c ../5-sqrt_recursion.c 
	$(CC) ../_putchar.c 5-main.c ../5-sqrt_recursion.c -o test5
test_6: ../_putchar.c 6-main.c ../6-is_prime_number.c 
	$(CC) ../_putchar.c 6-main.c ../6-is_prime_number.c -o test6
test_7: ../_putchar.c 100-main.c ../100-is_palindrome.c 
	$(CC) ../_putchar.c 100-main.c ../100-is_palindrome.c -o test7
test_7: ../_putchar.c 100-main.c ../101-wildcmp.c 
	$(CC) ../_putchar.c 100-main.c ../101-wildcmp.c -o test8 
clean:
	rm test
